### ISSUE TITLE
Change source of npm/node.js 

### ISSUE THREAD

**Issue by ghost** [CounterpartyXCP/federatednode#232]
```
curl -sL https://deb.nodesource.com/setup | sudo bash -
sudo apt-get install -y nodejs
```

Ref: https://github.com/nodesource/distributions

For v0.12 (not in releases yet): https://github.com/nodesource/distributions/issues/63#issuecomment-74580073
##

**Comment by unsystemizer** [comment]
Completed in https://github.com/CounterpartyXCP/federatednode_build/commit/a20696e8cfff6a630f1262d522f3c0b1465c24e5
