### ISSUE TITLE
run.py not handling switching from non-public to public server

### ISSUE THREAD

**Issue by jdogresorg** [CounterpartyXCP/federatednode#237]
the ‘run.py’ script does not seem to be respecting the command line args…. I am trying to change my config from a non-public server to a public server, and am having some issues.

sudo python3 run.py --role=counterwallet --autostart_services=y --server_public=y --branch=master --net=b --counterwallet_support_email=support@coindaddy.io --noninteractive

that does not do what you would expect…. it DOES NOT update the config files to change the username/pass to rpc:1234 as expected.
##

**Comment by unsystemizer** [comment]
It seems to me the CW role is supposed to only change email - https://github.com/CounterpartyXCP/federatednode_build/blob/master/run.py#L483
