### ISSUE TITLE
run.py update should not re-set CP passwords

### ISSUE THREAD

**Issue by ghost** [CounterpartyXCP/federatednode#240]
As per J-Dog: run.py script was updated to NOT automatically reset the passwords for counterparty
##

**Comment by robby-dermody** [comment]
is this a problem? the subject says it should not reset CP passwords, and the issue body says the script was updated to not automatically reset the passwords

**Comment by unsystemizer** [comment]
You can close this I think, I haven't noticed any password resets since then.
Maybe the original comment was edited.
