### ISSUE TITLE
configparser.NoSectionError: No section: 'Default'

### ISSUE THREAD

**Issue by got3nks** [CounterpartyXCP/federatednode#289]
cryptos@server:~/counterparty/federatednode$ fednode install full master
This script requires root access (via sudo) to run. Please enter your sudo password below.
[sudo] password for cryptos:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/configparser.py", line 1135, in _unify_values
    sectiondict = self._sections[section]
KeyError: 'Default'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/fednode", line 370, in <module>
    main()
  File "/usr/local/bin/fednode", line 215, in main
    build_config = config.get('Default', 'config')
  File "/usr/local/lib/python3.5/configparser.py", line 778, in get
    d = self._unify_values(section, vars)
  File "/usr/local/lib/python3.5/configparser.py", line 1138, in _unify_values
    raise NoSectionError(section)
configparser.NoSectionError: No section: 'Default'
##

**Comment by unsystemizer** [comment]
Are you on Ubuntu 16.04 x64?

**Comment by got3nks** [comment]
Yes I'm on Ubuntu 16.04, and I'm installing as non-root user.

**Comment by unsystemizer** [comment]
I tried earlier today and just now again (following install steps from http://counterparty.io/docs/federated_node/), works fine for me. 
I also tried to interrupt the install script while containers were downloading. Then I stopped Docker service, started it again, ran `fednode uninstall` and I was able to install fednode again. It seems to be able to handle minor disruptions.

**Comment by unsystemizer** [comment]
I ran into this today, because I had inconsistent federatednode configuration (yesterday I tried from `develop` and today from `master`).
I deleted the directory and repeated the git clone procedure and then install. It worked OK.
