### ISSUE TITLE
stop counterblock doesn't stop redis & mongodb

### ISSUE THREAD

**Issue by unsystemizer** [CounterpartyXCP/federatednode#297]
When I use `install counterblock develop` and stop services (counterparty, counterparty-testnet, bitcoin, bitcoin-testnet, counterblock, counterblock-testnet) using fednode command, these two remain:

```
$ sudo docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED              STATUS              PORTS                        NAMES
d4726ce080ee        redis:3.2           "docker-entrypoint..."   About a minute ago   Up About a minute   6379/tcp                     federatednode_redis_1
bde8f9910894        mongo:3.2           "docker-entrypoint..."   About a minute ago   Up About a minute   127.0.0.1:27017->27017/tcp   federatednode_mongodb_1
```
If these containers serve both mainnet and testnet data, then it's more difficult to determine when they should be shut down (presumably after the last remaining counterblock is shutdown, or with separate commands). 

I stop them with `fednode stop redis` and `fednode stop mongodb". 

Maybe this should be documented?

**Comment by robby-dermody** [comment]
sure, can you submit a PR to the fednode docs? (I'd rather document it, not automatically shut these services down) -- just a sentence in the appropriate spot should do, doesn't need to be extensive
