### ISSUE TITLE
"fednode install base master" failure

### ISSUE THREAD

**Issue by someone235** [CounterpartyXCP/federatednode#307]
I followed your instructions, but got few errors:

    $ fednode install base master
    Pulling bitcoin-testnet (counterparty/bitcoin:latest)...
    latest: Pulling from counterparty/bitcoin
    031c24a19e4b: Pull complete
    685982e65190: Pull complete
    8618fde1d092: Pull complete
    d610accf10b5: Pull complete
    b1b21aae4c77: Pull complete
    e6794a8eb162: Pull complete
    d4c26a98f374: Pull complete
    4bd05cec81a0: Pull complete
    539c8e3a398f: Pull complete
    7825f179d525: Pull complete
    023e2e955356: Pull complete
    58748c801a2b: Pull complete
    3234bf77c67e: Pull complete
    5190844ff443: Pull complete
    d6d142ebced2: Pull complete
    9bf183ce8c8c: Pull complete
    d337928337d3: Pull complete
    793f977c8edb: Pull complete
    69c803cdcc4b: Pull complete
    a043d8128c14: Pull complete
    2b57c0ead231: Pull complete
    d1b75b42cbe7: Pull complete
    123f0c0f8752: Pull complete
    Digest: sha256:0b381899f63bd097a6c6dad35476fcacd4ac5a344ad388b13141b7514aa15c67
    Status: Downloaded newer image for counterparty/bitcoin:latest
    Pulling bitcoin (counterparty/bitcoin:latest)...
    latest: Pulling from counterparty/bitcoin
    031c24a19e4b: Already exists
    685982e65190: Already exists
    8618fde1d092: Already exists
    d610accf10b5: Already exists
    b1b21aae4c77: Already exists
    e6794a8eb162: Already exists
    d4c26a98f374: Already exists
    4bd05cec81a0: Already exists
    539c8e3a398f: Already exists
    7825f179d525: Already exists
    023e2e955356: Already exists
    58748c801a2b: Already exists
    3234bf77c67e: Already exists
    5190844ff443: Already exists
    d6d142ebced2: Already exists
    9bf183ce8c8c: Already exists
    d337928337d3: Already exists
    793f977c8edb: Already exists
    69c803cdcc4b: Already exists
    a043d8128c14: Already exists
    2b57c0ead231: Already exists
    d1b75b42cbe7: Already exists
    123f0c0f8752: Already exists
    Digest: sha256:0b381899f63bd097a6c6dad35476fcacd4ac5a344ad388b13141b7514aa15c67
    Status: Image is up to date for counterparty/bitcoin:latest
    Pulling counterparty (counterparty/counterparty-server:latest)...
    latest: Pulling from counterparty/counterparty-server
    170fa84ea8d4: Pull complete
    2e02218c80a6: Pull complete
    dea4537e8f53: Pull complete
    162bf6d3a5ba: Pull complete
    c3224ed8b6c5: Pull complete
    bf0f0c4dd74c: Pull complete
    8e0862e56e9c: Pull complete
    22799f1b808e: Pull complete
    b1288b9da444: Pull complete
    bdae2268a518: Pull complete
    da1f03f5521f: Pull complete
    2c98bcf20588: Pull complete
    bed129549071: Pull complete
    d4809e92241b: Pull complete
    8b0cbba0fd63: Pull complete
    8088ebd4ea9d: Pull complete
    07ceb36bbc9a: Extracting [==========================================>        ] 616.1 MB/720.1 MB
    92965248afc0: Download complete
    a325ec098ace: Download complete
    f0a293876578: Download complete
    031c24a19e4b: Already exists
    685982e65190: Already exists
    8618fde1d092: Already exists
    d610accf10b5: Already exists
    b1b21aae4c77: Already exists
    e6794a8eb162: Already exists
    d4c26a98f374: Already exists
    4bd05cec81a0: Already exists
    539c8e3a398f: Already exists
    7825f179d525: Already exists
    023e2e955356: Already exists
    Pulling repository counterparty/counterparty-server
    ERROR: Repository not found
    Pulling counterparty-testnet (counterparty/counterparty-server:latest)...
    latest: Pulling from counterparty/counterparty-server
    07ceb36bbc9a: Extracting [=======================================>           ] 568.2 MB/720.1 MB
    92965248afc0: Download complete
    a325ec098ace: Download complete
    f0a293876578: Download complete
    031c24a19e4b: Already exists
    685982e65190: Already exists
    8618fde1d092: Already exists
    d610accf10b5: Already exists
    b1b21aae4c77: Already exists
    e6794a8eb162: Already exists
    d4c26a98f374: Already exists
    4bd05cec81a0: Already exists
    539c8e3a398f: Already exists
    7825f179d525: Already exists
    023e2e955356: Already exists
    170fa84ea8d4: Already exists
    2e02218c80a6: Already exists
    dea4537e8f53: Already exists
    162bf6d3a5ba: Already exists
    c3224ed8b6c5: Already exists
    bf0f0c4dd74c: Already exists
    8e0862e56e9c: Already exists
    22799f1b808e: Already exists
    b1288b9da444: Already exists
    bdae2268a518: Already exists
    da1f03f5521f: Already exists
    2c98bcf20588: Already exists
    bed129549071: Already exists
    d4809e92241b: Already exists
    8b0cbba0fd63: Already exists
    8088ebd4ea9d: Already exists
    Pulling repository counterparty/counterparty-server
    ERROR: Repository not found
    [sudo] password for ori: 
    docker: 'volume' is not a docker command. See 'docker --help'.
    docker: 'volume' is not a docker command. See 'docker --help'.
    Traceback (most recent call last):
      File "<string>", line 3, in <module>
      File "compose/cli/main.py", line 58, in main
      File "compose/cli/main.py", line 109, in perform_command
      File "compose/cli/main.py", line 734, in up
      File "compose/project.py", line 372, in up
      File "compose/project.py", line 413, in initialize
      File "compose/network.py", line 162, in initialize
      File "compose/network.py", line 47, in ensure
      File "compose/network.py", line 82, in inspect
      File ".tox/py27/lib/python2.7/site-packages/docker/utils/decorators.py", line 32, in wrapper
    docker.errors.InvalidVersion: inspect_network is not available for version < 1.21
    docker-compose returned -1
    
do you know what can I do to fix it?

**Comment by unsystemizer** [comment]
https://hub.docker.com/r/counterparty/counterparty-server/ seems available. Can you retry and see whether you get the same error?
Maybe you had a network or DNS timeout.

**Comment by unsystemizer** [comment]
I just installed following the docs (`fednode install counterblock master`) and it works fine. I think you had a network / DNS timeout.
