### ISSUE TITLE
Evaluate effect of rpcthreads setting

### ISSUE THREAD

**Issue by unsystemizer** [CounterpartyXCP/federatednode#313]
In https://github.com/CounterpartyXCP/counterparty-lib/blob/9.55.3/ChangeLog.md we removed the high-value rpcthreads setting, but in federatednode's bitcoin.conf.default (https://github.com/CounterpartyXCP/federatednode/tree/2.2.3/config/bitcoin) we keep it at 100.

The default is 4 so it's probably meant to be equal to number of cores. Maybe we should consider setting it to 8 or 16, or at least evaluate the effect of various values.

**Comment by unsystemizer** [comment]
Based on "from scratch" indexd tests done on testnet, the default values work quite well. Smaller systems may need even smaller values to avoid memory exhaustion.

**Comment by jdogresorg** [comment]
Issue was fixed in indexd a while ago, and fednode stack now uses addrindexrs instead of indexd.
