### ISSUE TITLE
Allow install with `--no-bootstrap` option

### ISSUE THREAD

**Issue by jdogresorg** [CounterpartyXCP/federatednode#338]
We should update fednode to allow a user to specify a `--no-bootstrap` option if they so desire.

Users could install Counterparty fednode with no bootstrap via the following command :
`fednode install full master --no-bootstrap`

When a user uses this `--no-bootstrap` option, it will require the fednode to create a new sqlite database with all the tables and indexes necessary for `counterparty-lib` to start parsing blocks at block 278270.

**Comment by jotapea** [comment]
@jdogresorg To be clear, this will also work with `base` installations correct?

(And some acknowledgement for the people involved in this idea would be appreciated 😉)

**Comment by jdogresorg** [comment]
correct, this new `--no-bootstrap` option would be available on all fednode installs (base, counterblock, full).

The default option will still be to use the bootstrap, but users should be able to use the following commands to install a fednode without any bootstrap in any of the mode

Base install (bitcoin/addrindexrs/counterparty):
`fednode install base master --no-bootstrap`

Counterblock Install (bitcoin/addrindexrs/counterblock/counterparty):
`fednode install counterblock master --no-bootstrap`

Full install (bitcoin/addrindexrs/counterblock/counterparty/counterwallet)
`fednode install full master --no-bootstrap`

**Comment by jdogresorg** [comment]
This `--no-bootstrap` option has been added to fednode in PR https://github.com/CounterpartyXCP/federatednode/pull/342
 and will be included in the next 9.60.1 release.
