### ISSUE TITLE
move to using docker for builds

### ISSUE THREAD

**Issue by robby-dermody** [CounterpartyXCP/federatednode#62]
**create Dockerfiles and build_docker.py script that will:**
- take a command line arg (or prompt) for the role to build
  - multiple docker files, one for each build config...e.g. counterwallet_simple, counterwallet_full, counterpartyd_only, etc
  - all docker files build off of https://github.com/phusion/baseimage-docker
- execute the build process to generate a docker image for the specified role
  - the Dockerfile will download and call setup_federated_node.py itself, to build the federated node in the docker image with the approprite command line options
    (we will use this all with automated builds on dockerhub, and each build variant will be a tag)

**Images I'd be planning:**
- counterwallet_bitcoind: Uses bitcoind, no insight (uses blockr.io), and auto downloads the bitcoind blockchain data and counterpartyd and counterblock databases on first boot via bittorrent or s3 site
- counterwallet_simple: Uses pyrpcwallet (and blockr.io), no insight (uses blockr.io), and auto downloads the counterpartyd and counterblock databases on first boot via bittorrent or s3 site
- counterpartyd_simple: Same as counterwallet_simple, but only runs counterpartyd, with open port access and rpc/1234 username/password on rpc services by default...allows easy dev counterpartyd access

**Future possible images:**
- counterwallet_full: Uses bitcoind and insight. Blockchain data must manually download
- vending_machine
- autobtcescrow_agent
- whatever else

**More notes:**
- build logic for everything except ubuntu 14.04 can then be ripped out (I'm thinking) of setup_federated_node.py since other OSes can just use the docker image. alert users to this because this is disruptive though
- ubuntu 14.04-based systems can still use setup_federated_node.py directly. this is especially important for production servers where we want everything to run on bare metal, and the hardware is dedicated (e.g. counterwallet.co)
- also, include plenty of documentation for using the docker images on windows, macos, and other versions of linux

**Docker resources:**
- https://gist.github.com/wsargent/7049221
- http://crosbymichael.com/dockerfile-best-practices-take-2.html
##

**Comment by unsystemizer** [comment]
@deweller this probably can be closed
